max_width=100
# format_code_in_doc_comments=true # unstable
newline_style="Unix"
use_field_init_shorthand=true
# use max_width instead of wierd precentages for certain items
use_small_heuristics="Max"
# I use a lot of derives and I hate one mega unreable list
merge_derives=false
